#!/bin/sh
#
# rcS		Call all S??* scripts in /etc/rcS.d in
#		numerical/alphabetical order.
#
# Version:	@(#)/etc/init.d/rcS  2.76  19-Apr-1999  miquels@cistron.nl
#

PATH=/sbin:/bin:/usr/sbin:/usr/bin
runlevel=S
prevlevel=N
umask 022
export PATH runlevel prevlevel

ROOTTMPMNT=/mnt/tmpRoot

DATAPARTITION=/dev/mmcblk1p6
DATATMPMNT=/mnt/data/

CONFIGOSPARTITION=/dev/mmcblk1p2
CONFIGOSTMPMNT=/mnt/configos/

ETCPARTITION=/dev/mmcblk1p5
ETCTMPMNT=/mnt/etcfs/

FACTORYPARTITION=/dev/mmcblk1p1
FACTORYTMPMNT=/mnt/factory/

#	Make sure proc is mounted
#
[ -d "/proc/1" ] || mount /proc

#
#	Source defaults.
#
. /etc/default/rcS

#
#	Trap CTRL-C &c only in this shell so we can interrupt subprocesses.
#
trap ":" INT QUIT TSTP

#
#      Verify mmcblk1p5 is populated (if no, copy /etc to it) and mount it over /etc 
# 
mount -t tmpfs -o rw,size=1M tmpfs /mnt

if [ "$ENABLE_ROOTFS_FSCK" = "yes" ]; then
  fsck -a $ETCPARTITION
fi

mkdir $ETCTMPMNT
mount $ETCPARTITION $ETCTMPMNT

if [ ! -d $ETCTMPMNT'init.d' ]; then
  # The partition does not contain a valid etc folder
  umount $ETCTMPMNT
  mke2fs -T ext3 -L "etc" $ETCPARTITION
  mount $ETCPARTITION $ETCTMPMNT
  cp -a /etc/. $ETCTMPMNT
  sync
fi

# Get etc and bsp versions
etcVers="$( cat $ETCTMPMNT/migrations/version )"
bspVers="$( cat /boot/version )"

#
#     Handle the user partition: mount it (format+mount if mount fails), copy the password file (shadow) 
#     if not yet there and make a link to it in the final /etc directory.
#

# Mount the factory partition (if mount fails, perform format+mount)
if [ "$ENABLE_ROOTFS_FSCK" = "yes" ]; then
  fsck -a $FACTORYPARTITION
fi

mkdir -p $FACTORYTMPMNT
mount $FACTORYPARTITION $FACTORYTMPMNT

if [ $? -ne 0 ]; then
   mke2fs -T ext3 -L "factory" $FACTORYPARTITION 
   mount $FACTORYPARTITION $FACTORYTMPMNT
fi

# If shadow in final etc partition is not a link to a valid file... copy /etc/shadow from original rootfs to the factory 
# partition and make a link to it in final etc partition
if [ ! -e $FACTORYTMPMNT'shadow' ] ; then
  cp -a /etc/shadow $FACTORYTMPMNT'shadow'
fi
if [ ! -L $ETCTMPMNT'shadow' ]; then
  ln -s -b $FACTORYTMPMNT'shadow' $ETCTMPMNT'shadow'
  chgrp shadow /etc/shadow
  sync
fi

mount -o remount,ro $FACTORYTMPMNT
umount $ETCTMPMNT
rmdir $ETCTMPMNT

# NOTE: we need to keep the factory partition mounted, in order not to break the link with the password file
# umount /mnt

# Switch to etc partition
mount $ETCPARTITION /etc 

# If versions do not match do postupdate
if [ ! "$etcVers" = "$bspVers" ]; then
	mkdir -p $ROOTTMPMNT
	mount -o bind / $ROOTTMPMNT
	$ROOTTMPMNT/etc/postupdate.sh $ROOTTMPMNT
	umount -l $ROOTTMPMNT
	rm -r $ROOTTMPMNT
fi

# Mount configos and data filesystems
if [ "$ENABLE_ROOTFS_FSCK" = "yes" ]; then
  fsck -a $CONFIGOSPARTITION
  fsck -a $DATAPARTITION
fi

mkdir $CONFIGOSTMPMNT
mkdir $DATATMPMNT
mount -o ro $CONFIGOSPARTITION $CONFIGOSTMPMNT
mount $DATAPARTITION $DATATMPMNT

# Move /home to data partition 
[ ! -d "$DATATMPMNT/home" ] && cp -rp /home $DATATMPMNT
mount -o bind $DATATMPMNT/home /home

#
#	Call all parts in order.
#
exec /etc/init.d/rc S
