#!/bin/sh
#
# rcS		Call all S??* scripts in /etc/rcS.d in
#		numerical/alphabetical order.
#
# Version:	@(#)/etc/init.d/rcS  2.76  19-Apr-1999  miquels@cistron.nl
#

PATH=/sbin:/bin:/usr/sbin:/usr/bin
runlevel=S
prevlevel=N
umask 022
export PATH runlevel prevlevel

ROOTTMPMNT=/mnt/tmpRoot

DATAPARTITION=/dev/mmcblk1p6
DATATMPMNT=/mnt/data/

CONFIGOSPARTITION=/dev/mmcblk1p2
CONFIGOSTMPMNT=/mnt/configos/

ETCTMPMNT=/mnt/etcfs/
ETCPARTITION=/dev/mmcblk1p5

FACTORYPARTITION=/dev/mmcblk1p1
FACTORYTMPMNT=/mnt/factory/

CMDFILE=$DATATMPMNT/updateCmd

# Mount system fs
mount -t proc proc /proc
mount -t sysfs sysfs /sys

# Source defaults.
. /etc/default/rcS
. /etc/exorint.funcs

if [ $ENABLE_FASTBOOT == "yes" ]
then
    echo "FastBoot enable";
    if [ -x /etc/init.d/rcS_fastboot ]
    then
        /etc/init.d/rcS_fastboot
        exit 0;
    fi;
else
    echo "FastBoot NOT enable";
fi;

# Trap CTRL-C &c only in this shell so we can interrupt subprocesses.
trap ":" INT QUIT TSTP

mount -t tmpfs -o rw,size=1M tmpfs /mnt

# Mount factory partition to get the splash image (if mount fails, perform format+mount)
mkdir $FACTORYTMPMNT
mount -o ro $FACTORYPARTITION $FACTORYTMPMNT
if [ $? -ne 0 ]; then
   mke2fs -T ext3 -L "factory" $FACTORYPARTITION
   mount -o ro  $FACTORYPARTITION $FACTORYTMPMNT
fi

# Copy /etc/shadow from etc to the factory partition if not already there
if [ ! -e $FACTORYTMPMNT'shadow' ] ; then
  mount -o remount,rw $FACTORYTMPMNT
  cp -a /etc/shadow $FACTORYTMPMNT'shadow'
  chgrp shadow $FACTORYTMPMNT'shadow'
  mount -o remount,ro $FACTORYTMPMNT
fi

[ "$ENABLE_ROOTFS_FSCK" = "yes" ] && fsck -a $ETCPARTITION

mount $ETCPARTITION /etc

# Read screen rotation settings
rotation=0
[ -s /etc/rotation ] && read rotation < /etc/rotation

# Disable console on framebuffer to avoid showing console output and
# blinking when starting X
echo 0 > /sys/class/vtconsole/vtcon1/bind

# Clear console framebuffer
echo -ne "\ec"  > /dev/tty1

# Clear framebuffer
[ -e /dev/fb0 ] && cat /dev/zero > /dev/fb0

# Start splash
export TMPDIR=/mnt/.psplash
mkdir $TMPDIR
mount -t tmpfs -o rw,size=40k /tmpfs $TMPDIR

if [ ! -z "$FASTBOOT" ] && [ -x /usr/bin/setoverlay ]; then
    #if we can use overlay, FB1 is used for psplash
    export FBDEV=/dev/fb1;
    #Create overlay!
    /usr/bin/setoverlay;
fi;

if [ ! -z "$FASTBOOT" ] && [ -x /usr/bin/xsplash ]; then
    #No close psplash when Xorg starts, is closed by xstarts
    psplash_opts='--no-console-switch'
fi;

/usr/bin/psplash --angle $rotation $psplash_opts &

# Verify etc partition is properly populated (if no, copy original /etc to it)
if [ ! -d '/etc/init.d' ]; then
   # The partition does not contain a valid etc folder
   umount -l /etc
   mke2fs -T ext3 -L "etc" $ETCPARTITION
   mkdir $ETCTMPMNT
   mount $ETCPARTITION $ETCTMPMNT
   cp -a /etc/. $ETCTMPMNT
   sync
   mount --move $ETCTMPMNT /etc
   rm -rf $ETCTMPMNT
fi

# Check if shadow in final etc partition is a link to a valid file 
if [ ! -L /etc/'shadow' ]; then
  ln -s -b $FACTORYTMPMNT'shadow' /etc/'shadow'
  sync
fi

# Get etc and bsp versions
etcVers="$( cat /etc/migrations/version )"
bspVers="$( cat /boot/version )"

# If versions do not match do postupdate
if [ ! "$etcVers" = "$bspVers" ]; then
   mkdir -p $ROOTTMPMNT
   mount -o bind / $ROOTTMPMNT
   . $ROOTTMPMNT/etc/migrations/postupdate.sh
   umount -l $ROOTTMPMNT
   rm -r $ROOTTMPMNT
fi

psplash-write "PROGRESS 0"

# NOTE: we need to keep the factory partition mounted, in order not to break the link with the password file
# umount /mnt

# Mount configos and data filesystems
if [ "$ENABLE_ROOTFS_FSCK" = "yes" ]; then
   fsck -a $CONFIGOSPARTITION
   fsck -a $DATAPARTITION
fi

if [ $ENABLE_FASTBOOT != "yes" ]
then
    mkdir $CONFIGOSTMPMNT
    mount -o ro $CONFIGOSPARTITION $CONFIGOSTMPMNT
    mkdir $DATATMPMNT
    mount -o usrquota,grpquota $DATAPARTITION $DATATMPMNT
else
    mkdir $DATATMPMNT
    mount -o usrquota,grpquota $DATAPARTITION $DATATMPMNT
fi

[ -e $CMDFILE ] && /etc/updateCmd.sh


exorint_fix_settings /mnt
exorint_data_quotaon $DATATMPMNT $QUOTA_DATA_RESERVED

# Move /home to data partition 
[ ! -d "$DATATMPMNT/home" ] && cp -rp /home $DATATMPMNT
mount -o bind $DATATMPMNT/home /home

# Post-processing - setup other links to factory (global settings)
[ ! -L /etc/pointercal.xinput ] && ln -sf $FACTORYTMPMNT/etc/pointercal.xinput /etc/pointercal.xinput
[ ! -L /etc/rotation ] && ln -sf $FACTORYTMPMNT/etc/rotation /etc/rotation
[ ! -L /etc/X11/xorg.conf.d/x11-rotate.conf ] && mkdir -p /etc/X11/xorg.conf.d && \
    ln -sf $FACTORYTMPMNT/etc/X11/xorg.conf.d/x11-rotate.conf /etc/X11/xorg.conf.d/x11-rotate.conf

# Update splash progress bar
PROGRESS_STATE=10
echo $PROGRESS_STATE > $TMPDIR/progress_state 
psplash-write "PROGRESS $PROGRESS_STATE"

# Blind device management
if [ "$(exorint_ver_type)" = "ROUTER" ]; then
    exorint_service_enable "router"
    # bootcounter reset - done by psplash for panels
    psplash-write "QUIT"
fi

# Call all parts in order
exec /etc/init.d/rc S
