#!/bin/bash

kill_pidfile()
{
    local pidfile="$1"
    local pid

    [ -e "${pidfile}" ] || return 0
    pid=$(cat "${pidfile}")

    echo "killing pid: ${pid}"
    kill ${pid} 2>/dev/null
    rm "${pidfile}"
}

kill_pidfile "/var/run/udhcpc-retry.$IFACE.pid"
kill_pidfile "/var/run/udhcpc.$IFACE.pid"

exit 0
