#!/bin/sh
#
# rcS		Call all S??* scripts in /etc/rcS.d in
#		numerical/alphabetical order.
#
# Version:	@(#)/etc/init.d/rcS  2.76  19-Apr-1999  miquels@cistron.nl
#

PATH=/sbin:/bin:/usr/sbin:/usr/bin
runlevel=S
prevlevel=N
umask 022
export PATH runlevel prevlevel


ETCTMPMNT=/mnt/etcfs/

FACTORYPARTITION=/dev/mmcblk1p1
FACTORYTMPMNT=/mnt/factory/

#	Make sure proc is mounted
#
[ -d "/proc/1" ] || mount /proc

#
#	Source defaults.
#
. /etc/default/rcS

#
#	Trap CTRL-C &c only in this shell so we can interrupt subprocesses.
#
trap ":" INT QUIT TSTP

#
#      Verify mmcblk1p5 is populated (if no, copy /etc to it) and mount it over /etc 
# 
mount -t tmpfs -o rw tmpfs /mnt
mkdir $ETCTMPMNT

# creates a temporary rambased etcfs
mount -o bind /etc $ETCTMPMNT
# mount a volatile temporary fs in /etc copying files from original /etc
mount -t tmpfs -o rw tmpfs /etc
cp -a $ETCTMPMNT/* /etc/
umount $ETCTMPMNT
rmdir $ETCTMPMNT

# Mount the factory partition (if mount fails, perform format+mount)
if [ "$ENABLE_ROOTFS_FSCK" = "yes" ]; then
  fsck -a $FACTORYPARTITION
fi

mkdir $FACTORYTMPMNT
mount $FACTORYPARTITION $FACTORYTMPMNT

if [ $? -ne 0 ]; then
   mke2fs -T ext3 -L "factory" $FACTORYPARTITION 
   mount $FACTORYPARTITION $FACTORYTMPMNT
fi
# creates a link
if [ ! -e $FACTORYTMPMNT'shadow' ] ; then
  cp -a /etc/shadow $FACTORYTMPMNT'shadow'
fi
ln -s -b $FACTORYTMPMNT'shadow' /etc/shadow
chgrp shadow /etc/shadow

# Mount mainos and data filesystems
if [ "$ENABLE_ROOTFS_FSCK" = "yes" ]; then
  fsck -a $MAINOSPARTITION
  fsck -a $DATAPARTITION
fi

#
#	Call all parts in order.
#
exec /etc/init.d/rc S


