#!/bin/sh

[ "$IFACE" = "lo" ] && exit 0

# scripts here are not guaranteed to run only once..
LOCK="/tmp/avahi-restart.lock"
[ -e "${LOCK}" ] && exit 0

[ -e /etc/rc5.d/S[0-9][0-9]avahi-daemon ] || exit 0

{
    touch "${LOCK}"

    /etc/init.d/avahi-daemon restart

    rm "${LOCK}"

} &

exit 0
