#!/bin/sh

# Scripts here are not guaranteed to run only once..
LOCK="/tmp/ntpsync.lock"
[ -e "${LOCK}" ] && exit 0

# if ntpd is not running we assume "Automatic Update" is disabled - do nothing
pidof ntpd > /dev/null || exit 0

{
    touch "${LOCK}"

    /etc/init.d/ntpd stop

    SERVER=`grep ^server /etc/ntp.conf | head -n 1 | awk '{print $2}'`
    ntpdate "${SERVER}" && hwclock -u -w

    /etc/init.d/ntpd start

    rm "${LOCK}"

} &

exit 0
